version: "3.9"

services:
    master:
        image: master
        ports: 
            - 8080:8080
        links:
            - "instagram:instagram"
    instagram:
        image: instagram-crawler
        ports: 
            - 8000:8000
        environment:
            - username=sociolitic
            - password=pesusmmpanel