version: "3.9"

services:
    data:
        image: sociolitic/data-crawlers
        ports:
            - 5000:5000
    master:
        image: nithinsgowda/sociolitic
        ports: 
            - 8080:8080
            - 7000:7000
        links:
            - "data:data"