version: "3.9"

services:
    master:
        image: nithinsgowda/sociolitic
        ports: 
            - 8080:8080
    data-crawler:
        image: sociolitic/data-crawlers
        ports:
            - 5000:5000